//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PedidosFacturacion
{
    using System;
    using System.Collections.Generic;
    
    public partial class Canasto
    {
        public int Id { get; set; }
        public Nullable<int> Id_pedido { get; set; }
        public Nullable<int> Id_local { get; set; }
        public Nullable<int> Numero_local { get; set; }
        public string Descripcion_local { get; set; }
        public Nullable<int> Id_vendedor { get; set; }
        public Nullable<int> Legajo_vendedor { get; set; }
        public string Descripcion_vendedor { get; set; }
        public string Segmento { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
        public string Estado { get; set; }
        public Nullable<System.DateTime> Fecha_asignacion { get; set; }
        public Nullable<System.DateTime> Fecha_facturacion { get; set; }
        public Nullable<int> Id_asignador { get; set; }
        public Nullable<int> Legajo_asignador { get; set; }
        public string Descripcion_asignador { get; set; }
        public Nullable<int> Id_facturista { get; set; }
        public Nullable<int> Legajo_facturista { get; set; }
        public string Descripcion_facturista { get; set; }
        public string Prioridad { get; set; }
        public string Comentario { get; set; }
    
        public virtual Operario Operario { get; set; }
        public virtual Operario Operario1 { get; set; }
        public virtual Local Local { get; set; }
        public virtual Operario Operario2 { get; set; }
        public virtual Pedido Pedido { get; set; }
    }
}
