//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PedidosFacturacion
{
    using System;
    using System.Collections.Generic;
    
    public partial class Canasto
    {
        public int Id { get; set; }
        public Nullable<int> Id_Local { get; set; }
        public Nullable<int> Numero_Local { get; set; }
        public string Descripcion_Local { get; set; }
        public Nullable<int> Id_Vendedor { get; set; }
        public Nullable<int> Legajo_Vendedor { get; set; }
        public string Descripcion_Vendedor { get; set; }
        public string Estado { get; set; }
        public string Segmento { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
    }
}
