//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PedidosFacturacion
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PedidosDBEntities : DbContext
    {
        public PedidosDBEntities()
            : base("name=PedidosDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Canasto> Canastoes { get; set; }
        public DbSet<Estado> Estadoes { get; set; }
        public DbSet<Local> Locals { get; set; }
        public DbSet<Operario> Operarios { get; set; }
        public DbSet<Pedido> Pedidos { get; set; }
        public DbSet<Segmento> Segmentoes { get; set; }
        public DbSet<sysdiagram> sysdiagrams { get; set; }
        public DbSet<Usuario> Usuarios { get; set; }
    }
}
