//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PedidosFacturacion
{
    using System;
    using System.Collections.Generic;
    
    public partial class Operario
    {
        public Operario()
        {
            this.Canastoes = new HashSet<Canasto>();
            this.Canastoes1 = new HashSet<Canasto>();
            this.Canastoes2 = new HashSet<Canasto>();
        }
    
        public int Id { get; set; }
        public int Legajo { get; set; }
        public string Descripcion { get; set; }
    
        public virtual ICollection<Canasto> Canastoes { get; set; }
        public virtual ICollection<Canasto> Canastoes1 { get; set; }
        public virtual ICollection<Canasto> Canastoes2 { get; set; }
    }
}
