//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PedidosFacturacion
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pedidos
    {
        public int Id { get; set; }
        public int Id_Canasto { get; set; }
        public Nullable<System.DateTime> Fecha_canasto { get; set; }
        public Nullable<System.DateTime> Fecha_asignacion { get; set; }
        public Nullable<System.DateTime> Fecha_facturacion { get; set; }
        public string Prioridad { get; set; }
        public Nullable<int> Id_asignador { get; set; }
        public Nullable<int> Legajo_asignador { get; set; }
        public string Descripcion_asignador { get; set; }
        public Nullable<int> Id_facturista { get; set; }
        public Nullable<int> Legajo_Facturista { get; set; }
        public string Descripcion_facturista { get; set; }
        public string Comentario { get; set; }
    }
}
