//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PedidosFacturacion
{
    using System;
    using System.Collections.Generic;
    
    public partial class Segmentos
    {
        public int Id { get; set; }
        public string Hombre { get; set; }
        public string Mujer { get; set; }
        public string Kids { get; set; }
    }
}
